### ISSUE TITLE
App Shortcut not working?

### ISSUE THREAD

**Issue by ghost** [ServiceStack/dotnet-app#4]
I can launch my app just fine using the command:
**_app MVCDemoApp.exe_**

What I am trying to do is create a desktop shortcut that the user can launch just by double-clicking it.
I think the command I want is:
**_app shortcut MVCDemoApp.exe_**

When I do this, all I get is the help listing for the app command. Am I doing this right? Is there any more documentation for the 'app shortcut' command?

Thanks, 

Len.

**Comment by mythz** [comment]
Apologies functionality was skipped in a recent refactor, resolved in [this commit](https://github.com/ServiceStack/dotnet-app/commit/bfd3da4662f0c0b6bd790bf1c636abe101a94868). 

This fix is available from **v0.0.68** which has just been published to nuget.org but I've seen nuget take up to 30 mins before they finish indexing the package and make it available to update to, when **v0.0.68** is available you can upgrade with:

    $ dotnet tool update -g app
