### ISSUE TITLE
latest release 0.0.81 seems busted?

### ISSUE THREAD

**Issue by Beej126** [ServiceStack/dotnet-app#5]
i resolved [this issue with service stack studio](https://github.com/ServiceStack/Studio/issues/1) by downgrading to ss 'app' tool to 0.79
0.80 actually had a different issue (missing BCL reference error)

**Comment by mythz** [comment]
The studio app's binary dependency just needed to rebuilt, you'll now be able to launch it using the latest `app` tool, e.g:

    $ dotnet tool update -g app
    $ app open studio
