### ISSUE TITLE
observerations attempting to build on mac

### ISSUE THREAD

**Issue by johndpope** [ServiceStack/dotnet-app#7]
the team I work with is building dotnet 6 app - I'd like to use on mac. 
when I run 
**docker build .**

it fails 

docker build .
[+] Building 0.6s (13/18)                                                                                                   
 => [internal] load build definition from Dockerfile                                                                   0.0s
 => => transferring dockerfile: 867B                                                                                   0.0s
 => [internal] load .dockerignore                                                                                      0.0s
 => => transferring context: 2B                                                                                        0.0s
 => [internal] load metadata for mcr.microsoft.com/dotnet/sdk:5.0                                                      0.3s
 => [internal] load build context                                                                                      0.0s
 => => transferring context: 25B                                                                                       0.0s
 => CANCELED [build 1/8] FROM mcr.microsoft.com/dotnet/sdk:5.0@sha256:c5df98ac266e6cd2b94c3ac4e153d7e43db0a84b833b125  0.0s
 => => resolve mcr.microsoft.com/dotnet/sdk:5.0@sha256:c5df98ac266e6cd2b94c3ac4e153d7e43db0a84b833b125cada852ec16edd7  0.1s
 => => sha256:c5df98ac266e6cd2b94c3ac4e153d7e43db0a84b833b125cada852ec16edd752 2.17kB / 2.17kB                         0.0s
 => => sha256:d8e8e2bc5e652402685754b72747bed99579aec4bfd5c6f13cb964bfa47ed2ae 2.01kB / 2.01kB                         0.0s
 => => sha256:d90b87c477ea8f8b1196de55dd785d2fb504de6aec0bba3a1d60750d8db6f3d9 7.15kB / 7.15kB                         0.0s
 => CACHED [build 2/8] WORKDIR /src                                                                                    0.0s
 => ERROR [build 3/8] COPY /src/GistRun/GistRun.csproj ./                                                              0.0s
 => CACHED [build 4/8] RUN dotnet nuget add source https://www.myget.org/F/servicestack -n myget.org                   0.0s
 => CACHED [build 5/8] RUN dotnet restore                                                                              0.0s
 => ERROR [build 6/8] COPY /src/GistRun .                                                                              0.0s
 => CACHED [build 7/8] RUN dotnet publish -c Release -o /app/publish   --no-restore                                    0.0s
 => ERROR [build 8/8] COPY /src/GistRun/NuGet.Config /app/publish                                                      0.0s
 => ERROR [final 2/7] COPY /src/GistRun/prefetch.sh ./                                                                 0.0s
------
 > [build 3/8] COPY /src/GistRun/GistRun.csproj ./:
------
------
 > [build 6/8] COPY /src/GistRun .:
------
------
 > [build 8/8] COPY /src/GistRun/NuGet.Config /app/publish:
------
------
 > [final 2/7] COPY /src/GistRun/prefetch.sh ./:
------
failed to compute cache key: "/src/GistRun/GistRun.csproj" not found: not found

**Comment by mythz** [comment]
The DockerFile isn't used by this repo.

What project did you want to build?

**Comment by mythz** [comment]
If you're trying to install the [x dotnet tool](https://docs.servicestack.net/dotnet-tool) on [Apple M1](https://docs.servicestack.net/dotnet-tool#apple-m1) did you try:

```bash
dotnet tool install -g -a x64 x
```

**Comment by johndpope** [comment]
I want to get docker + dot net 6 + service stack (any kind of sample code) / if you know of any hello world samples - would appreciate it - I will try command above tomorrow thanks.

**Comment by mythz** [comment]
FYI If you just want start with an empty ServiceStack project, you can create it from the website without installing any tools:

### https://servicestack.net/start
